apiVersion: v1
kind: Services
metadata:
  name: shoppingcart-service
spec:
  selector:
    app: shoppingcart
  type: LoadBalancer
  port:
  - protocol: TCP
    port: 8080
    targetport: 8080
    nodePort: 31110