apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-service
spec:
  selector:
    app: shoppingcart 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31110